version: "2.0"
services:
  interview-app:
    image: closeit-interview:0.0.1
    ports:
      - 8080:8080 # Replace the port of your application here if used
    depends_on:
      - interview-db
  interview-db:
    image: mongo
    volumes:
      - ./database:/data
    ports:
      - "27017:27017"